try{
    ..
}catch(RuntimeException e){
   log(e);
   throw e;
}catch(ExceptionException ..){
   log(e);
   throw e;
}