try{
    assertEquals(true, true);
}catch (AssertionError ex) {
    //Do Something
    throw(ex);
}