try {
    //do something
}catch(IOException ex){

    //handle error here
}