void method2() {
    try {
        // Error here
    } catch(Exception e) {
        throw e;
    }
}